### PR TITLE
Fix two buttons in saved schedule

### LINKED ISSUE #63: Two buttons in saved schedule
In the Saved Schedule page, two buttons are being added by the extension:

image

### PR DESCRIPTION
**Pull request by raymond212**
Fixes the issue of adding buttons when the user is on the "Find Course Sections for Saved Schedule" page. 

resolves #63

### CODE REVIEW

**Comment by Rileyc2022** [comment]
Thank you for the PR. There definitely shouldn't be two of our '+'  buttons, but maybe there should be one of our buttons, so our extension is still usable on this page. For example, what if a user decides at that page to add a new section to their workday worklist, and wants to also add it to our extension to easily check for conflicts before proceeding? I don't really see how it helps the user to not have that functionality here.

**Comment by mlool** [comment]
Is this PR goof to go?

**Comment by raymond212** [comment]
I think so, but we might want another opinion.

**Comment by mlool** [comment]
@Rileyc2022 What do you think?

**Pull request merged**
