### PR TITLE
[Feature] Add term-specific "Clear" Feature & Highlight important info (completed #89)

### PR DESCRIPTION
**Pull request by YuluDuan**
Letting users reset either Term 1 or Term 2 individually without affecting the rest of their schedule #89 
Screen Shot 2024-06-06 at 11 37 32 PM

### CODE REVIEW

**Comment by mlool** [comment]
Term specific clear causes interaction bugs, especially with 2 term courses. More thoughts need to go into this. Won't merge for now

**Comment by YuluDuan** [comment]
> Term specific clear causes interaction bugs, especially with 2 term courses. More thoughts need to go into this. Won't merge for now

Hi Martin, thanks for the comment. Could you please expand more on the potential interaction bugs that may occur?

**Comment by mlool** [comment]
Hey Yulu, I think I just worry when someone clear worklists, not sure what we should do with the 2 term courses, as the section details are sometimes string string "2024 - 2025" or "2024 - 2024, 2025 - 2025" which would introduce quite a number of hard coded checks. Which we don't want. One issue you could potentially look into is for courses with multiple locations, how can we split it so that the location corresponds with the time instead of all listed in all the sections.

**Comment by YuluDuan** [comment]
> Hey Yulu, I think I just worry when someone clear worklists, not sure what we should do with the 2 term courses, as the section details are sometimes string string "2024 - 2025" or "2024 - 2024, 2025 - 2025" which would introduce quite a number of hard coded checks. Which we don't want. One issue you could potentially look into is for courses with multiple locations, how can we split it so that the location corresponds with the time instead of all listed in all the sections.

I see, thank you, Martin! I will take a look at it

**Pull request closed without merging**
