### PR TITLE
Added button on page to add a section

### PR DESCRIPTION
**Pull request by Rileyc2022**
Added a button on the Workday page next to each section. When you click it, it adds the section to the schedule. Makes it a bit easier to use.

### CODE REVIEW

**Comment by Vaten0x** [comment]
I don't see the button either from your branch.

**Comment by Rileyc2022** [comment]
Hm weird okay. I just committed the build maybe try that. It's supposed to look like this:
Screen Shot 2024-05-28 at 12 57 57 PM

**Comment by Vaten0x** [comment]
Weird, do you wanna talk about it through discord? I still don't see it

**Comment by Vaten0x** [comment]
it worked now sorry
image

**Review by mlool — APPROVED** [review]
I see it now, thanks for the feature

**Comment by Rileyc2022** [comment]
Great thanks guys

**Pull request merged**
